version: '3.7'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    links:
      - db
    depends_on:
      - db
    container_name: api
    ports:
      - '4000:4000'
    build:
      context: flag-api
      dockerfile: Dockerfile
    volumes:
      - ./flag-api:/app
      - /app/node_modules
      - /app/prisma
  admin:
    links:
      - api
    depends_on:
      - api
    container_name: admin
    ports:
      - '3000:3000'
    build:
      context: flag-admin
      dockerfile: Dockerfile
